### PR TITLE
Fix `removevredundancy!`

### LINKED ISSUE #52: BUG: `removevredundancy!` removes wrong row
Related to #51

```julia
A = [0 1 0; -1 0 0; 0 -1 0; 0 0 -1; 1 0 0]
b = [2, -1, -1, -1, 2]
linset = BitSet(5)
hr = hrep(A, b, linset)
p = polyhedron(hr, LRSLib.Library())
removevredundancy!(p)
p
```

```
Polyhedron LRSLib.Polyhedron:
1-element iterator of HyperPlane{Rational{BigInt}, Vector{Rational{BigInt}}}:
 HyperPlane(Rational{BigInt}[1, 0, 0], 2//1),
4-element iterator of HalfSpace{Rational{BigInt}, Vector{Rational{BigInt}}}:
 HalfSpace(Rational{BigInt}[0, 1, 0], 2//1)
 HalfSpace(Rational{BigInt}[-1, 0, 0], -1//1)
 HalfSpace(Rational{BigInt}[0, -1, 0], -1//1)
 HalfSpace(Rational{BigInt}[0, 0, -1], -1//1):
1-element iterator of Vector{Rational{BigInt}}:
 Rational{BigInt}[2, 1, 1],
2-element iterator of Ray{Rational{BigInt}, Vector{Rational{BigInt}}}:
 Ray(Rational{BigInt}[0, 0, 1])
 Ray(Rational{BigInt}[0, 0, 1])
```

```julia
p.ext.R
```

```
3×4 Matrix{Rational{BigInt}}:
 1  2  1  1
 0  0  0  1
 0  0  0  1
```

In https://github.com/JuliaPolyhedra/LRSLib.jl/blob/22915a1c3f47bad262e685c6f3ef6311113480da/src/polyhedron.jl#L183-L196 `redund(extm)` returns **0-based** indices (output from a C program!). That should be modified to be consistent with Julia's 1-based indexing.

### PR DESCRIPTION
**Pull request by oyamad**
Fix #52
* d38598431ac0a62a8bbe65ac72f22b46eed1743c fixes https://github.com/JuliaPolyhedra/LRSLib.jl/issues/52#issue-2794736460
* 2fa1210c3a545c5ba5361027a937f7a31fe48804 fixes https://github.com/JuliaPolyhedra/LRSLib.jl/issues/52#issuecomment-2599525572

Closes https://github.com/JuliaPolyhedra/LRSLib.jl/pull/50

### CODE REVIEW

**Comment by blegat** [comment]
You can update `redund` directly here:
https://github.com/JuliaPolyhedra/LRSLib.jl/blob/22915a1c3f47bad262e685c6f3ef6311113480da/src/redund.jl#L34
by pushing `ineq + 1`
and here
https://github.com/JuliaPolyhedra/LRSLib.jl/blob/22915a1c3f47bad262e685c6f3ef6311113480da/src/redund.jl#L40
You can replace `ineq::Int` by `ineq::Polyhedra.Index`.
Then it's clear we are talking about 1-based indexing because of:
https://github.com/JuliaPolyhedra/LRSLib.jl/blob/22915a1c3f47bad262e685c6f3ef6311113480da/src/matrix.jl#L230

File: src/polyhedron.jl [hunk 1]
```diff
@@ -55,8 +55,6 @@ function getine(p::Polyhedron)
         else
             p.ine = LiftedHRepresentation(getextm(p, :Fresh))
             p.inem = nothing
-            p.hlinearitydetected = true
```
Comment (blegat) [inline src/polyhedron.jl:58]: Leave the setting of `hlinearitydetected` here and add a mention to the issue to say that in some examples there are still redundant elements

Comment (oyamad) [reply src/polyhedron.jl:58]: Changed back `p.hlinearitydetected = true` and `p.vlinearitydetected = true` in `getine` and `getext`.

(By the way, please feel free to edit this branch.)

**Comment by oyamad** [comment]
Pushing `ineq + 1` in `redund` generates many errors; see #54.

**Comment by oyamad** [comment]
@blegat Is it possible that for H-representation, the first column (row 0 in the C indexing) is used for the objective function, while it is not case for V-representation? (I.e., Does "row i" point to different rows between H- and V-representations?)
https://github.com/JuliaPolyhedra/LRSLib.jl/blob/22915a1c3f47bad262e685c6f3ef6311113480da/src/matrix.jl#L51-L54
https://github.com/JuliaPolyhedra/LRSLib.jl/blob/22915a1c3f47bad262e685c6f3ef6311113480da/src/matrix.jl#L77-L80

**Comment by blegat** [comment]
Yes, and you always need to set an objective for the H-rep:
https://github.com/JuliaPolyhedra/LRSLib.jl/blob/22915a1c3f47bad262e685c6f3ef6311113480da/src/matrix.jl#L51-L54

**Comment by oyamad** [comment]
I think I understand the things now.
* `redund` returns 0-based indices, and `removevredundancy!` takes them as 1-based indices, and so it removes wrong rows.
* The same applies to `removehredundancy!`, but for H-representation, the top row is reserved for the objective, and therefore `removehredundancy!` removes correct rows (by coincidence).

The bug can be fixed by either
* adding 1 to the output of `redund(extm)` in `removevredundancy!` (this PR);
or
* adding 1 to `ineq` in `redund` and subtracting 1 in the output of `redund(inem)` in `detectvlinearity!` (#54).

Each of this PR and #54 is ready to merge. Please choose one!

**Review by blegat — APPROVED** [review]
Thanks! Let's merge this one as it is non-breaking for `redund` then we'll see if we want to additionally make a breaking change
